[firebase]
apiKey = "AIzaSyCPcSizfdyHKd231kDqEAh38IT-dxVtFm4"
authDomain = "cbse-class-10-result-tracker.firebaseapp.com"
projectId = "cbse-class-10-result-tracker"
storageBucket = "cbse-class-10-result-tracker.firebasestorage.app"
messagingSenderId = "445558959211"
appId = "1:445558959211:web:7efa45c11fd3d7eb6bd52e"
measurementId = "G-7XQ81C28PH"

fcm_vapid_key = "usFi3orjmpd8lxqJFm39DVMLCWMOZBe08Dqe5SbmQr4"
